version: "3.7"
services:
  hip-atomfeed-listener:
    container_name: hip-atomfeed-listener
    image: bahmniindiadistro/hip-atomfeed
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/
      - DATABASE_NAME=hip-atomfeed-listener
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=welcome
      - OPENMRS_URL=https://abdm.bahmni-covid19.in/openmrs/ws/rest/v1/session
      - OPENMRS_ENCOUNTER_FEED_URL=https://abdm.bahmni-covid19.in/openmrs/ws/atomfeed/encounter/recent
      - OPENMRS_USERNAME=
      - OPENMRS_PASSWRD=
      - PHONE_NUMBER=
      - HIP_URL=https://abdm.bahmni-covid19.in/hiprovider
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=welcome
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data:
