replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmniindiadistro
  name: hip-atomfeed
  tag: latest

service:
  type: ClusterIP
  port: 80

config:
  DATABASE_URL: "jdbc:postgresql://bahmni-dev-postgresql:5432/"
  DATABASE_NAME: "hip-atomfeed-listener"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "welcome"
  OPENMRS_URL: "http://bahmni-openmrs:8080/openmrs"
  OPENMRS_ENCOUNTER_FEED_URL: "http://bahmni-openmrs:8080/openmrs/ws/atomfeed/encounter/recent"


autoscaling:
  enabled: false