global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmniindiadistro
  name: hip-atomfeed
  tag: latest

service:
  type: ClusterIP
  port: 80

config:
  DATABASE_URL: "jdbc:postgresql://bahmni-dev-postgresql:5432/"
  DATABASE_NAME: "hip_atomfeed_listener"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "welcome"
  OPENMRS_URL: "http://openmrs:8080/openmrs/ws/rest/v1/session"
  OPENMRS_ENCOUNTER_FEED_URL: "http://openmrs:8080/openmrs/ws/atomfeed/encounter/recent"
  HIP_URL: "http://hip:8000"


autoscaling:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: {}

